### ISSUE TITLE
Checklist so I feel like I'm making progress

### ISSUE THREAD

**Issue by Sparky939** [Sparky939/godbound#4]
- [x] Remove Spell Items to see if it just loads
- [x] Bug Testing
- [ ] Attribute Modifiers - doesn't handle above 19 or below 2
- [ ] Attribute Rolls - TypeError: can't access property "value", this.attributes[attributeId] is undefined
- [ ] Save Rolls - Just doesn't work - no error reported
- [ ] Next Level - incorrectly reports level 1 requirements at level 1
- [ ] Level - Not correctly updating for XP & Dominion Spent
- [x] Health - input box not big enough for double digits
- [ ] Effort - Can have negative effort
- [ ] Weapon - Roll formula is wrong
- [ ] Weapon - Roll formula should have a natural display (non-formula)
- [ ] Weapon - Roll formula doesn't update for selected attribute
- [ ] Weapon - Roll doesn't roll damage
- [x] Armour - There is no AC display on the sheet
- [ ] Armour - Worn Armour with penalties doesn't appear to affect saves
- [ ] Words - There's no Words or Gifts section
- [ ] Gifts Items - List of Words not updated dynamically with settings

**Comment by Sparky939** [comment]
Created oustanding functionality as Issues
